homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.5488
  longitude: -3.5958
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 50
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  #Customisations
  #customise: !include_dir_list customise/

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

###########################
## SENSORS
###########################

sensor: !include includes/sensors.yaml

###########################
## IFTTT
###########################

#IFTTT Support
ifttt:
  key: !secret ifttt_key
  
###########################
## MEDIA PLAYERS
###########################

#Chromecast
media_player: !include includes/media.yaml

###########################
## SWITCHES
###########################

switch: !include includes/switches.yaml

###########################
## iFrames
###########################

panel_iframe: !include iframe.yaml
  
###########################
## Groups
###########################

group: !include group.yaml

###########################
## Automation
###########################

#automation: !include_dir_merged_list automation/
